# General
command_timeout = 2000
palette = "catppuccin_mocha"

format = """
$directory\
$git_branch\
${custom.git_clean}\
${custom.git_dirty}\
$nodejs\
$python\
$rust\
$docker_context\
$line_break\
$character"""

# Prompt character
[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

# Directory
[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncation_length = 0
truncate_to_repo = false
style = "bold purple"

# Git
[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
symbol = " "
style = "bold blue"

[git_status]
disabled = true

[custom.git_dirty]
command = "echo ✖"
require_repo = true
when = '[ -n "$(git status --porcelain 2>/dev/null)" ]'
style = "bold red"
format = " [$output]($style)"

[git_metrics]
disabled = true

[custom.git_clean]
command = "echo ●"
require_repo = true
when = '[ -z "$(git status --porcelain 2>/dev/null)" ]'
style = "bold green"
format = " [$output]($style)"

# Node.js
[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

# Python
[python]
symbol = " "
format = "[$symbol($version )]($style)"

# Docker
[docker_context]
symbol = " "
format = "[$symbol$context]($style)"

[aws]
disabled = true

[gcloud]
disabled = true

[java]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[golang]
disabled = true

[kotlin]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
